misc

diff --git a/home/bin/chat b/home/bin/chat
--- a/home/bin/chat
+++ b/home/bin/chat
@@ -84,7 +84,17 @@ _sta=$?
 
 [ "$flag_l" ] && { echo "$models"; exit 0; }
 
-echo "$models" | grep -qFx "$opt_m" || error "model \"$opt_m\" is not available"
+# echo "$models" | grep -qFx "$opt_m" || error "model \"$opt_m\" is not available"
+# opt_m_fuzzy=$(echo "$opt_m" | sed 's/./.*&/g')
+model=$(echo "$models" | grep -Fi "$opt_m")
+case "$?" in
+    (0) ;;
+    (*) error "model \"$opt_m\" is not found" ;;
+esac
+case "$(echo "$model" | wc -l)" in
+    (1) ;;
+    (*) error "model \"$opt_m\" is ambiguous" ;;
+esac
 
 
 ## Tools
@@ -148,7 +158,7 @@ trap cleanup INT TERM
 # note: avoid including arbitrarily large strings in command parameter (use pipe instead)
 
 # shellcheck disable=SC2016
-jq -s --arg m "$opt_m" --arg s "$opt_s" --argjson t "$tools_api" \
+jq -s --arg m "$model" --arg s "$opt_s" --argjson t "$tools_api" \
     '{model:$m,stream:true,tools:$t,messages:[{role:"system",content:$s},.[]]}' \
     "$histfile" \
     | stdbuf -o0 curl -fNs "$opt_u"/v1/chat/completions -d @- \
