misc

diff --git a/home/bin/chat b/home/bin/chat
--- a/home/bin/chat
+++ b/home/bin/chat
@@ -1,20 +1,31 @@
 #!/bin/sh
 
-default_u=localhost:11434 default_s='Respond concisely /no_think'
-flag_e= flag_h= flag_l= flag_n=
-opt_m= opt_s=$default_s opt_u=$default_u
+NEWL='
+'
+
+default_u=localhost:11434; default_s='Respond concisely /no_think'
+flag_c=; flag_e=; flag_h=; flag_l=; flag_n=
+opt_m=; opt_s=$default_s; opt_u=$default_u
 prompt=''
+# shellcheck disable=SC2016
+# Duplicate : to escape it
+tools='get_time:get current time:timezone=time zone:format=format (you can use %Y %m %d %H %M %S):TZ=$timezone date +"$format"
+list_files:list files in dir:dir=directory (use . for current dir):recursive=if nonempty, list files recusively:ls "${recursive::+-R}" "$dir"
+cat_file:show contents of a file:path=path to the file:cat "$path"'
+# TODO require tool confirm (e.g. by prefix its name with !)
 
 while [ $# -ge 1 ]; do
     case "$1" in
         (-[!-][!-]*)  _1=${1#?} ; shift ; set -- "-${_1%"${_1#?}"}" "-${_1#?}" "$@" ;;
-        (-e|--erase)   flag_e=1  ; shift ;;
-        (-h|--help)    flag_h=1  ; shift ;;
-        (-l|--list)    flag_l=1  ; shift ;;
-        (-n|--noout)   flag_n=1  ; shift ;;
-        (-m|--model)   opt_m="$2"; shift 2 ;;
-        (-s|--system)  opt_s="$2"; shift 2 ;;
-        (-u|--url)     opt_u="$2"; shift 2 ;;
+        (-c|--continue) flag_c=1  ; shift ;;
+        (-e|--erase)    flag_e=1  ; shift ;;
+        (-h|--help)     flag_h=1  ; shift ;;
+        (-l|--list)     flag_l=1  ; shift ;;
+        (-n|--noout)    flag_n=1  ; shift ;;
+        (-m|--model)    opt_m="$2"; shift 2 ;;
+        (-s|--system)   opt_s="$2"; shift 2 ;;
+        (-u|--url)      opt_u="$2"; shift 2 ;;
+        (-t|--tool)     tools="$tools$NEWL$2"; shift 2 ;;
         (*) prompt="$*" ; break ;;
     esac
 done
@@ -26,18 +37,26 @@ help(){
     echo "       cmd | $0 [options ...]"
     echo
     echo "Options:"
+    echo "  -c, --continue         Continue upon previous tool calling"
     echo "  -e, --erase            Erase history before starting"
     echo "  -h, --help             Help"
     echo "  -l, --list             List models"
     echo "  -m, --model <model>    Model         (default: auto)"
     echo "  -n, --noout            No chat output file (still creates history)"
     echo "  -s, --system <prompt>  System prompt (default: $default_s)"
+    echo "  -t, --tool <spec>      Define additional tools"
     echo "  -u, --url <url>        URL of server (default: $default_u)"
+    echo
+    echo "Tool spec example:"
+    echo "$tools"
 }
 
 error(){
     echo "Error: $*" >&2; exit 1
 }
+
+
+## Various checks
 
 missing=
 for i in curl jq stdbuf; do
@@ -63,25 +82,15 @@ _sta=$?
 
 echo "$models" | grep -qFx "$opt_m" || error "model \"$opt_m\" is not available"
 
-outdir=$HOME/.cache/chat/
-mkdir -p "$outdir"
 
-outfile="$outdir"/chat-"$(date +%Y%m%d-%H%M%S)".txt
-[ "$flag_n" ] && outfile=${TMPDIR:-/tmp}/chat-out
+## Tools
 
-tmpfile=${TMPDIR:-/tmp}/chat-hist
-[ "$flag_e" ] && rm -f "$tmpfile"
-[ -f "$tmpfile" ] || touch "$tmpfile"
+tools_api=$(echo "$tools" | jq -R '[sub("::";"=x=x=";"g")|split(":")[]|sub("=x=x=";":";"g")]|{type:"function",function:{name:.[0],description:.[1],parameters:.[2:-1]|{type:"object",required:[.[]|split("=")[0]],properties:[.[]|split("=")|{key:.[0],value:{type:"string",description:.[1]}}]|from_entries}}}' | jq -s .)
+tools_int=$(echo "$tools" | jq -R '[sub("::";"=x=x=";"g")|split(":")[]|sub("=x=x=";":";"g")]|{key:.[0],value:.[-1]}' | jq -s 'from_entries')
 
-cleanup(){
-    [ "$flag_n" ] && rm -f "$outfile"
-}
+# printf "tools_api=%s\ntools_int=%s\n" "$tools_api" "$tools_int" >&2; exit
 
-trap cleanup INT TERM
-
-# note: avoid including arbitrarily large strings in command parameter (use pipe instead)
-
-#tools="[{
+# tools="[{
 #    \"type\": \"function\",
 #    \"function\": {
 #        \"name\": \"get_time\",
@@ -94,125 +103,67 @@ trap cleanup INT TERM
 #            \"required\": [\"timezone\"]
 #        }
 #    }
-#}]"
+# }]"
 
-if [ -t 0 ]; then printf %s "$prompt"; else cat; fi \
-    | tee "$outfile" \
-    | jq -Rs '{role:"user",content:.}' \
-    >> "$tmpfile"
 
-printf "\n\n" >> "$outfile"
+## Build query
 
-jq -s --arg m "$opt_m" --arg s "$opt_s" --argjson t '[]' \
+histfile=${TMPDIR:-/tmp}/chat-hist
+[ "$flag_e" ] && rm -f "$histfile"
+touch "$histfile"
+
+if [ ! "$flag_c" ]; then
+    if [ -t 0 ]; then printf %s "$prompt"; else cat; fi \
+        | jq -Rs '{role:"user",content:.}' \
+        >> "$histfile"
+fi
+
+outdir=$HOME/.cache/chat/
+mkdir -p "$outdir"
+outfile="$outdir"/chat-"$(date +%Y%m%d-%H%M%S)".txt
+[ "$flag_n" ] && outfile=${TMPDIR:-/tmp}/chat-out
+{
+    jq -r 'if .content then "<\(.role)>\n\(.content)\n" else empty end' "$histfile"
+    printf "<assistant>\n"
+} > "$outfile"
+
+cleanup(){ [ ! "$flag_n" ] || rm -f "$outfile"; }
+trap cleanup INT TERM
+
+
+## Main API call
+
+# note: avoid including arbitrarily large strings in command parameter (use pipe instead)
+
+# shellcheck disable=SC2016
+jq -s --arg m "$opt_m" --arg s "$opt_s" --argjson t "$tools_api" \
     '{model:$m,stream:true,tools:$t,messages:[{role:"system",content:$s},.[]]}' \
-    "$tmpfile" \
+    "$histfile" \
     | stdbuf -o0 curl -fNs "$opt_u"/v1/chat/completions -d @- \
-    | stdbuf -i0 -o0 jq -Rcj --unbuffered 'foreach (inputs|if startswith("data: {") then .[6:] else empty end|fromjson) as $x ([null];[$x,.[0]];.)|. as [$x,$y]|(try $y.choices[].delta.reasoning_content catch false) as $pr|if $x.timings then ["\n",($x.timings|{model:$x.model,prompt_ms,predicted_ms,predicted_n,predicted_per_second})][] else ($x.choices[].delta|if .reasoning_content then (if $pr then .reasoning_content else ["\u001b[35m",.reasoning_content][] end) elif .content then (if $pr then ["\u001b[0m\n",.content][] else .content end) elif .tool_calls then .tool_calls[0]|(if .id then "TOOL: \(.function.name) " else .function.arguments end) else empty end) end' \
+    | stdbuf -i0 -o0 tee /tmp/chat-res-"$(date +%s)" \
+    | stdbuf -i0 -o0 jq -Rcj --unbuffered 'foreach (inputs|if startswith("data: {") then .[6:] else empty end|fromjson) as $x ([null];[$x,.[0]];.)|. as [$x,$y]|(try $y.choices[].delta.reasoning_content catch false) as $pr|if $x.timings then [(if $pr then "\u001b[0m\n" else empty end),"\nTIME: ",($x.timings|{model:$x.model,prompt_ms,predicted_ms,predicted_n,predicted_per_second}),"\n"][] else ($x.choices[].delta|if .reasoning_content then .reasoning_content|[(if $pr then empty else "\u001b[35m" end),.][] else (if .content then .content elif .tool_calls then .tool_calls[0]|((if .id then "TOOL: \(.function.name) " else "" end)+.function.arguments) else empty end)|[(if $pr then "\u001b[0m\n" else empty end),.][] end) end' \
     | stdbuf -i0 -o0 tee -a "$outfile"
 
-[ -f "$outfile" ] || exit 0
-
-sed -n '$q;3,$p' "$outfile" \
+# shellcheck disable=SC2016
+tac "$outfile" | awk -v a="$(printf '\033[35m')" -v b="$(printf '\033[0m')" '/^(TIME|TOOL): /{next}/^<assistant>$/{exit}index($0,b){f=1}(!f){print}index($0,a){f=0}' | tac \
     | jq -Rs '{role:"assistant",content:.}' \
-    >> "$tmpfile"
+    >> "$histfile"
 
-##!/bin/sh
-#
-#MODEL=${MODEL:-Qwen3-32B}
-#SERVER=${SERVER:-localhost:18034}
-#NEWL='
-#'
-#S(){ stdbuf -o0 "$@"; }
-#
-#prompt=
-#tools=
-#while [ $# -ge 1 ]; do
-#    case "$1" in
-#        (-t) echo tool "$2" ; tools="$tools$NEWL$2" ; shift 2 ;;
-#        (*) prompt="$prompt$1 " ; shift ;;
-#    esac
-#done
-#tools='get_time:get current time:timezone=time zone:format=format (you can use %Y %m %d %H %M %S):TZ=$timezone date +"$format"
-#list_files:list files in dir:dir=directory:ls "$dir"
-#cat_file:show contents of a file:path=path to the file:cat "$path"'
-#
-#tools_api=$(echo "$tools" | jq -R 'split(":")|{type:"function",function:{name:.[0],description:.[1],parameters:.[2:-1]|{type:"object",required:[.[]|split("=")[0]],properties:[.[]|split("=")|{key:.[0],value:{type:"string",description:.[1]}}]|from_entries}}}' | jq -s .)
-#
-#echo "tools_api=$tools_api"
-#tools_int=$(echo "$tools" | jq -R 'split(":")|{key:.[0],value:.[-1]}' | jq -s 'from_entries')
-#echo "tools_int=$tools_int"
-#
-#now=$(date +%Y%m%d-%H%M%S)
-#tmp=./"$now"
-#
-#jq -n --arg prompt "$prompt" '[{"role":"user","content":$prompt}]' > "$tmp-msg1"
-#
-#while :; do
-#
-#    messages="$(cat "$tmp-msg1")"
-#
-#    req=$(jq -n --arg model "$MODEL" --argjson tools_api "$tools_api" --argjson messages "$messages" '{"model":$model,"stream":true,"tools":$tools_api,"messages":([{"role":"system","content":"Respond concisely. /no_think"}]+$messages)}')
-#
-#    # echo "req=$req"
-#    echo "Requesting $messages"
-#
-#    S curl -sN "$SERVER/v1/chat/completions" -d "$req" | jq --unbuffered -nR '
-#    reduce inputs as $y (
-#        { raw: "", msgs: [] };
-#        .raw+=$y+"\n" as $acc
-#        |if ($y|startswith("data: {")) then
-#           ($y|.[6:]|fromjson|.choices[0].delta) as $x
-#           |if $x.role then
-#               ($acc|.msgs+=[{role:$x.role,content:""}])
-#           elif ($x.reasoning_content // $x.content) then
-#               (($x.reasoning_content // $x.content) as $z|($z|stderr)|
-#                   $acc|.msgs[-1].content+=$z)
-#           elif $x.tool_calls then
-#               $x.tool_calls[0] as $y|(
-#                   if $y.function.name then
-#                       (("Tool: \($y.function.name) "|stderr)|
-#                           ($acc|.msgs+=[{role:"tool_call",name:$y.function.name,arguments:""}]))
-#                   else
-#                       (($y.function.arguments|stderr)|
-#                           ($acc|.msgs[-1].arguments+=$y.function.arguments))
-#                   end
-#               )
-#           else
-#               $acc # necessary
-#           end
-#        end
-#    )
-#    ' > "$tmp-res"
-#    echo
-#
-#    jq -r .raw "$tmp-res" > "$tmp-raw"
-#    jq .msgs "$tmp-res" > "$tmp-msg2"
-#    # cat "$tmp-msg2"
-#    jq -s 'flatten' "$tmp-msg1" "$tmp-msg2" > "$tmp-msg3"
-#
-#    tool_call=$(jq -r --argjson tools_int "$tools_int" '
-#    [.[]|select(.role == "tool_call")]
-#    |if length >= 1 then
-#        .[-1] | (([.arguments|fromjson|to_entries[]|"\(.key)=\(.value|@sh)"]|join("; ")) + "; " +  $tools_int[.name])
-#    else
-#        empty
-#    end
-#    ' "$tmp-msg3")
-#
-#    if [ "$tool_call" ]; then
-#        echo "Tool call: $tool_call"
-#        tool_result=$(eval "$tool_call" 2>&1)
-#        echo "Result: $tool_result"
-#        jq --arg tool_result "$tool_result" '[.[]|select(.role != "tool_call")] + [{role:"tool",content:$tool_result}]' "$tmp-msg3" > "$tmp-msg4"
-#        cat "$tmp-msg4" > "$tmp-msg1"
-#    else
-#        echo "Finished. More prompt? "
-#        read -r prompt
-#        if [ "$prompt" ]; then
-#            jq -n --arg prompt "$prompt" '.+[{"role":"user","content":$prompt}]' "$tmp-msg3" > "$tmp-msg1"
-#        else
-#            break
-#        fi
-#    fi
-#
-#done
+
+## Tool call
+
+tool_call=$(sed -n 's/^TOOL: //p' "$outfile")
+if [ "$tool_call" ]; then
+    tool_cmd=$(echo "$tool_call" | jq -rR --argjson t "$tools_int" 'split(" ")|[.[0],(.[1:]|join(" ")|fromjson|[to_entries[]|"\(.key|@sh)=\(.value|@sh)"]|join(" "))]|"env \(.[1]) sh -c \($t[.[0]]|@sh)"')
+    tool_result=$(eval "$tool_cmd")
+    printf "\ncmd:  %s\nout:  %s\n\n" "$tool_cmd" "$tool_result" >&2
+    id=$(date +"tc_%Y%m%d_%H%M%S")
+    printf %s "$tool_call" | jq -Rsr --arg id "$id" 'split(" ")|{role:"assistant",tool_calls:[{id:$id,type:"function",function:{name:.[0],arguments:(.[1:]|join(" "))}}]}' >> "$histfile"
+    printf %s "$tool_result" | jq -Rsr --arg id "$id" '{role:"tool",tool_call_id:$id,content:.}' >> "$histfile"
+    "$0" -u "$opt_u" -m "$opt_m" -c "${flag_n:+-n}"
+fi
+
+
+## Cleanup
+
+cleanup
