misc

diff --git a/home/bin/xcopy b/home/bin/xcopy
--- a/home/bin/xcopy
+++ b/home/bin/xcopy
@@ -2,22 +2,36 @@
 
 text=$1
 
-if command -v xclip >/dev/null; then # xorg
-    if [ -z "$text" ]; then
-        xclip -selection clipboard -i
+wsl_enc() { # fix encoding: accepts utf-8 or shift-jis and writes utf-8
+    wsl_enc_in=/tmp/wslenctmp1
+    wsl_enc_out=/tmp/wslenctmp2
+    cat > "$wsl_enc_in"
+    echo 0 >&2
+    if iconv -f shift-jis -t shift-jis <"$wsl_enc_in" >"$wsl_enc_out" 2>/dev/null; then
+        echo 1 >&2
+        cat "$wsl_enc_out"
+    elif iconv -f utf-8 -t shift-jis <"$wsl_enc_in" >"$wsl_enc_out" 2>/dev/null; then
+        echo 2 >&2
+        cat "$wsl_enc_out"
     else
-        echo "$text" | xclip -selection clipboard -i
+        echo 3 >&3
+        cat "$wsl_enc_in"
     fi
+}
 
-elif command -v clip.exe > /dev/null; then # wsl
-    # & is necessary because operations are slow
-    if [ -z "$text" ]; then
-        # perl -pe 'chomp if eof' 2>/dev/null | iconv -f utf-8 -t shift-jis -c | clip.exe &
-        perl -pe 'chomp if eof' 2>/dev/null | clip.exe &
-    else
-        # echo "$text" | perl -pe 'chomp if eof' 2>/dev/null | iconv -f utf-8 -t shift-jis -c | clip.exe &
-        echo "$text" | perl -pe 'chomp if eof' 2>/dev/null | clip.exe &
-    fi
+if [ -n "${IS_WSL}${WSL_DISTRO_NAME}${WSL_INTEROP}${WSL_ENV}" ]; then # wsl
+    cd / # might fail if pwd is network shared directory etc. so always cd to /
+    cat | iconv -f utf-8 -t shift-jis | sh -c "clip.exe" &
+    # clip.exe < /dev/stdin & # not work from nvim
+    # cat | clip.exe & # works, but sometimes slow
+    # cat | sh -c "clip.exe" & # works and fast (why?)
+    # Also, must give shift-jis text to clip.exe (otherwise garbage when pasting on windows)
+    # { [ -z "$text" ] && cat || echo "$text"; } \
+    #     | wsl_enc | sh -c "clip.exe" &
+
+elif command -v xclip >/dev/null; then # xorg
+    { [ -z "$text" ] && cat || echo "$text"; } \
+        | xclip -selection clipboard -i
 
 fi
 
